# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mysecretpassword
  jta:
    atomikos:
      datasource:
        unique-resource-name: APP
        local-transaction-mode: true
        min-pool-size: 20
        max-pool-size: 30
      properties:
        transaction-manager-unique-name: ibmmq
      connectionfactory:
        max-pool-size: 2
        local-transaction-mode: true
  sql:
    init:
      continue-on-error: true
      mode: always

atomikos:
  properties:
    transaction-manager-unique-name: logcloud

logging:
  pattern:
    console:
  file:
    name: ibmmq.log
    logback:
    rollingpolicy:
      clean-history-on-start: true
    pattern:
      file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    "[ROOT]": WARN

ibm:
  mq:
    queueManager: QM1
    channel: DEV.APP.SVRCONN
    connName: localhost(1414)
    user: app
    password: apppass123
